### ISSUE TITLE
Animated Gifs?

### ISSUE THREAD

**Issue by anthonyjdella** [martinohanlon/quickdraw_python#12]
First off thanks for this API!

When I get and save an image, it's saved as a gif file extension, however, it isn't animated. 
Is there a way to save each image as a gif with animations (showing each stroke from the drawings)?

```
anvil = qd.get_drawing("anvil")
anvil.image.save("../images/my_anvil.gif")
```

**Comment by martinohanlon** [comment]
Yes, the API doesnt work this way. `image` returns a completed image of all the pen strokes. I dont suppose it would be too difficult to add a `get_animation` method which returns a list PIL Image objects.

You could use the data returned by [QuickDrawing.strokes](https://quickdraw.readthedocs.io/en/latest/api.html#quickdraw.QuickDrawing.strokes) to construct an animated GIF.

**Comment by martinohanlon** [comment]
I thought this was quite fun and wanted a short task to do, so I have added this the ability to save animations of the drawing.

```python
from quickdraw import QuickDrawData

qd = QuickDrawData()

anvil = qd.get_drawing("anvil",)
anvil.animation.save("my_anvil_animation.gif")
```

It also gave me the chance to update things like python versions.

**Comment by martinohanlon** [comment]
You will need to update quickdraw using pip

e.g. 

```
pip3 install quickdraw --upgrade
```

**Comment by agithony** [comment]
@martinohanlon Thanks so much! This is incredible! 🎉
