### ISSUE TITLE
Question regarding API and Endpoints?

### ISSUE THREAD

**Issue by OmaymaS** [martinohanlon/quickdraw_python#8]
Hi,

I was just wondering if Quickdraw doesn't offer a public API, how do you have access to the whole dataset? I was planning to create an API in another language and was not sure if there was a public API or a developer version?!

Thanks

**Comment by martinohanlon** [comment]
Sorry for the late response. Notifications for this repo were turned off.

I dont know if this is the "full" data but there is an API available at https://github.com/googlecreativelab/quickdraw-dataset
